// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: support_teachers.proto

package user_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SupportTeacherService_Create_FullMethodName  = "/support_teachers.SupportTeacherService/Create"
	SupportTeacherService_GetById_FullMethodName = "/support_teachers.SupportTeacherService/GetById"
	SupportTeacherService_GetAll_FullMethodName  = "/support_teachers.SupportTeacherService/GetAll"
	SupportTeacherService_Update_FullMethodName  = "/support_teachers.SupportTeacherService/Update"
	SupportTeacherService_Delete_FullMethodName  = "/support_teachers.SupportTeacherService/Delete"
)

// SupportTeacherServiceClient is the client API for SupportTeacherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SupportTeacherServiceClient interface {
	Create(ctx context.Context, in *CreateSupportTeacher, opts ...grpc.CallOption) (*SupportTeacher, error)
	GetById(ctx context.Context, in *SupportTeacherPrimaryKey, opts ...grpc.CallOption) (*SupportTeacher, error)
	GetAll(ctx context.Context, in *GetListSupportTeachersRequest, opts ...grpc.CallOption) (*GetListSupportTeachersResponse, error)
	Update(ctx context.Context, in *UpdateSupportTeacher, opts ...grpc.CallOption) (*SupportTeacher, error)
	Delete(ctx context.Context, in *SupportTeacherPrimaryKey, opts ...grpc.CallOption) (*Empty, error)
}

type supportTeacherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSupportTeacherServiceClient(cc grpc.ClientConnInterface) SupportTeacherServiceClient {
	return &supportTeacherServiceClient{cc}
}

func (c *supportTeacherServiceClient) Create(ctx context.Context, in *CreateSupportTeacher, opts ...grpc.CallOption) (*SupportTeacher, error) {
	out := new(SupportTeacher)
	err := c.cc.Invoke(ctx, SupportTeacherService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supportTeacherServiceClient) GetById(ctx context.Context, in *SupportTeacherPrimaryKey, opts ...grpc.CallOption) (*SupportTeacher, error) {
	out := new(SupportTeacher)
	err := c.cc.Invoke(ctx, SupportTeacherService_GetById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supportTeacherServiceClient) GetAll(ctx context.Context, in *GetListSupportTeachersRequest, opts ...grpc.CallOption) (*GetListSupportTeachersResponse, error) {
	out := new(GetListSupportTeachersResponse)
	err := c.cc.Invoke(ctx, SupportTeacherService_GetAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supportTeacherServiceClient) Update(ctx context.Context, in *UpdateSupportTeacher, opts ...grpc.CallOption) (*SupportTeacher, error) {
	out := new(SupportTeacher)
	err := c.cc.Invoke(ctx, SupportTeacherService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supportTeacherServiceClient) Delete(ctx context.Context, in *SupportTeacherPrimaryKey, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, SupportTeacherService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupportTeacherServiceServer is the server API for SupportTeacherService service.
// All implementations must embed UnimplementedSupportTeacherServiceServer
// for forward compatibility
type SupportTeacherServiceServer interface {
	Create(context.Context, *CreateSupportTeacher) (*SupportTeacher, error)
	GetById(context.Context, *SupportTeacherPrimaryKey) (*SupportTeacher, error)
	GetAll(context.Context, *GetListSupportTeachersRequest) (*GetListSupportTeachersResponse, error)
	Update(context.Context, *UpdateSupportTeacher) (*SupportTeacher, error)
	Delete(context.Context, *SupportTeacherPrimaryKey) (*Empty, error)
	mustEmbedUnimplementedSupportTeacherServiceServer()
}

// UnimplementedSupportTeacherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSupportTeacherServiceServer struct {
}

func (UnimplementedSupportTeacherServiceServer) Create(context.Context, *CreateSupportTeacher) (*SupportTeacher, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSupportTeacherServiceServer) GetById(context.Context, *SupportTeacherPrimaryKey) (*SupportTeacher, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedSupportTeacherServiceServer) GetAll(context.Context, *GetListSupportTeachersRequest) (*GetListSupportTeachersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedSupportTeacherServiceServer) Update(context.Context, *UpdateSupportTeacher) (*SupportTeacher, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSupportTeacherServiceServer) Delete(context.Context, *SupportTeacherPrimaryKey) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSupportTeacherServiceServer) mustEmbedUnimplementedSupportTeacherServiceServer() {}

// UnsafeSupportTeacherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SupportTeacherServiceServer will
// result in compilation errors.
type UnsafeSupportTeacherServiceServer interface {
	mustEmbedUnimplementedSupportTeacherServiceServer()
}

func RegisterSupportTeacherServiceServer(s grpc.ServiceRegistrar, srv SupportTeacherServiceServer) {
	s.RegisterService(&SupportTeacherService_ServiceDesc, srv)
}

func _SupportTeacherService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSupportTeacher)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportTeacherServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportTeacherService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportTeacherServiceServer).Create(ctx, req.(*CreateSupportTeacher))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupportTeacherService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupportTeacherPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportTeacherServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportTeacherService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportTeacherServiceServer).GetById(ctx, req.(*SupportTeacherPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupportTeacherService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListSupportTeachersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportTeacherServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportTeacherService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportTeacherServiceServer).GetAll(ctx, req.(*GetListSupportTeachersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupportTeacherService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSupportTeacher)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportTeacherServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportTeacherService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportTeacherServiceServer).Update(ctx, req.(*UpdateSupportTeacher))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupportTeacherService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupportTeacherPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportTeacherServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportTeacherService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportTeacherServiceServer).Delete(ctx, req.(*SupportTeacherPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

// SupportTeacherService_ServiceDesc is the grpc.ServiceDesc for SupportTeacherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SupportTeacherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "support_teachers.SupportTeacherService",
	HandlerType: (*SupportTeacherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SupportTeacherService_Create_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _SupportTeacherService_GetById_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _SupportTeacherService_GetAll_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SupportTeacherService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SupportTeacherService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "support_teachers.proto",
}
