// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: branches.proto

package user_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BranchesService_Create_FullMethodName  = "/branches.BranchesService/Create"
	BranchesService_GetById_FullMethodName = "/branches.BranchesService/GetById"
	BranchesService_GetAll_FullMethodName  = "/branches.BranchesService/GetAll"
	BranchesService_Update_FullMethodName  = "/branches.BranchesService/Update"
	BranchesService_Delete_FullMethodName  = "/branches.BranchesService/Delete"
)

// BranchesServiceClient is the client API for BranchesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BranchesServiceClient interface {
	Create(ctx context.Context, in *CreateBranch, opts ...grpc.CallOption) (*Branch, error)
	GetById(ctx context.Context, in *BranchePrimaryKey, opts ...grpc.CallOption) (*Branch, error)
	GetAll(ctx context.Context, in *GetListBranchesRequest, opts ...grpc.CallOption) (*GetListBranchesResponse, error)
	Update(ctx context.Context, in *UpdateBranch, opts ...grpc.CallOption) (*Branch, error)
	Delete(ctx context.Context, in *BranchePrimaryKey, opts ...grpc.CallOption) (*Empty, error)
}

type branchesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBranchesServiceClient(cc grpc.ClientConnInterface) BranchesServiceClient {
	return &branchesServiceClient{cc}
}

func (c *branchesServiceClient) Create(ctx context.Context, in *CreateBranch, opts ...grpc.CallOption) (*Branch, error) {
	out := new(Branch)
	err := c.cc.Invoke(ctx, BranchesService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *branchesServiceClient) GetById(ctx context.Context, in *BranchePrimaryKey, opts ...grpc.CallOption) (*Branch, error) {
	out := new(Branch)
	err := c.cc.Invoke(ctx, BranchesService_GetById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *branchesServiceClient) GetAll(ctx context.Context, in *GetListBranchesRequest, opts ...grpc.CallOption) (*GetListBranchesResponse, error) {
	out := new(GetListBranchesResponse)
	err := c.cc.Invoke(ctx, BranchesService_GetAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *branchesServiceClient) Update(ctx context.Context, in *UpdateBranch, opts ...grpc.CallOption) (*Branch, error) {
	out := new(Branch)
	err := c.cc.Invoke(ctx, BranchesService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *branchesServiceClient) Delete(ctx context.Context, in *BranchePrimaryKey, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, BranchesService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BranchesServiceServer is the server API for BranchesService service.
// All implementations must embed UnimplementedBranchesServiceServer
// for forward compatibility
type BranchesServiceServer interface {
	Create(context.Context, *CreateBranch) (*Branch, error)
	GetById(context.Context, *BranchePrimaryKey) (*Branch, error)
	GetAll(context.Context, *GetListBranchesRequest) (*GetListBranchesResponse, error)
	Update(context.Context, *UpdateBranch) (*Branch, error)
	Delete(context.Context, *BranchePrimaryKey) (*Empty, error)
	mustEmbedUnimplementedBranchesServiceServer()
}

// UnimplementedBranchesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBranchesServiceServer struct {
}

func (UnimplementedBranchesServiceServer) Create(context.Context, *CreateBranch) (*Branch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBranchesServiceServer) GetById(context.Context, *BranchePrimaryKey) (*Branch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedBranchesServiceServer) GetAll(context.Context, *GetListBranchesRequest) (*GetListBranchesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedBranchesServiceServer) Update(context.Context, *UpdateBranch) (*Branch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedBranchesServiceServer) Delete(context.Context, *BranchePrimaryKey) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBranchesServiceServer) mustEmbedUnimplementedBranchesServiceServer() {}

// UnsafeBranchesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BranchesServiceServer will
// result in compilation errors.
type UnsafeBranchesServiceServer interface {
	mustEmbedUnimplementedBranchesServiceServer()
}

func RegisterBranchesServiceServer(s grpc.ServiceRegistrar, srv BranchesServiceServer) {
	s.RegisterService(&BranchesService_ServiceDesc, srv)
}

func _BranchesService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBranch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchesServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BranchesService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchesServiceServer).Create(ctx, req.(*CreateBranch))
	}
	return interceptor(ctx, in, info, handler)
}

func _BranchesService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BranchePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchesServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BranchesService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchesServiceServer).GetById(ctx, req.(*BranchePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _BranchesService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListBranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchesServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BranchesService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchesServiceServer).GetAll(ctx, req.(*GetListBranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BranchesService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBranch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchesServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BranchesService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchesServiceServer).Update(ctx, req.(*UpdateBranch))
	}
	return interceptor(ctx, in, info, handler)
}

func _BranchesService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BranchePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchesServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BranchesService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchesServiceServer).Delete(ctx, req.(*BranchePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

// BranchesService_ServiceDesc is the grpc.ServiceDesc for BranchesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BranchesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "branches.BranchesService",
	HandlerType: (*BranchesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BranchesService_Create_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _BranchesService_GetById_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _BranchesService_GetAll_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BranchesService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BranchesService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "branches.proto",
}
